config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  devise_for :users, path_names:{
    :sign_in => 'login',
    :sign_out => 'logout' 
  }, 
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
   
  resources :menus
  resources :orders do
    collection do
      get "get_menu"
      post "filter_data"
    end
  end
  resources :sales_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
	include Discard::Model
	default_scope -> { kept }
	before_create :set_available_quantity
	before_update :update_available_quantity

	validates_presence_of :name
	validates :quantity, presence: true, numericality: { only_integer: true }
	validates :price, presence: true, numericality: true 

	has_many :menu_orders
	has_many :orders, through: :menu_orders

	self.per_page = 10

	private
		def set_available_quantity
			self.available_quantity = self.quantity			
		end

		def update_available_quantity
			if quantity_changed?
				quantity_update = quantity - quantity_was
				self.available_quantity = self.available_quantity + quantity_update
			end
		end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :check_role
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]
 
  def index
    @menus = Menu.paginate(:page => params[:page]).order(id: :asc)
    @menus_count = @menus.count/Menu.per_page
    unless @menus.count%Menu.per_page == 0
      @menus_count = @menus_count + 1
    end
  end

 
  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_item_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menus_path, notice: 'New Menu item is created successfuly.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @menu.update(menu_item_params)
        format.html { redirect_to menus_path, notice: 'Menu Item is updated successfully.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.discard
    respond_to do |format|
      format.html { redirect_to menus_path(page: params[:page]), notice: 'Menu Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_role
      if current_user.role.name == "Sales"
        redirect_to root_path, notice: "You have not permission to access Menu Items."
      end
    end

    def set_menu_item
      @menu = Menu.find(params[:id])
    end

    def menu_item_params
      params.require(:menu).permit(:name, :price, :quantity)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<div class="input-field col s12">
  <%= f.text_field :name, autofocus: true, validate: true, class: "validate" %>
  <%= f.label :name %>
  <span class="helper-text" data-error=""></span>
</div>
<div class="input-field col s12">
  <%= f.text_field :quantity, validate: { presence: true }, class: "validate"%>
  <%= f.label :quantity %>
  <span class="helper-text" data-error="" ></span>
</div>
<div class="input-field col s12">
  <%= f.number_field :price, validate: { presence: true }, class: "validate"%>
  <%= f.label :price %>
  <span class="helper-text" data-error="" ></span>
</div>

app/views/menus/edit.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s9">
      <h4>Edit Menu Item</h4>
    </div>
  </div>
  <div class="row">
    <%= form_for(@menu, class: "col s12", validate: true) do |f| %>
      <div class="row">
        <%= render "form", f: f %>
        <div class="input-field col s12">
          <button type="submit" name="commit" value="Update Menu" class="waves-effect waves-light btn col s12" data-disable-with="Update Menu">Update Menu</bottun>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/index.html.erb
<div class="row">
  <div class="col s9">
    <h3>Menu Items</h3>
  </div>
  <div class="col s3 right-align">
    <%= link_to new_menu_path, class: "btn-floating btn-large waves-effect waves-light red margin-top-15" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
</div>
<table class="responsive-table centered">
  <thead>
    <tr>
        <th>Item Number</th>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Availabe Quantity</th>
        <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each_with_index do |menu, index|%>
      <tr>
        <td><%= params[:page].present? ? (((params[:page].to_i - 1) * Menu.per_page)  + index + 1) : index + 1 %></td>
        <td><%= menu.name %></td>
        <td>$<%= menu.price %></td>
        <td><%= menu.quantity %></td>
        <td><%= menu.available_quantity %></td>
        <td>
          <%= link_to edit_menu_path(menu) do %>
            <i class="material-icons">edit</i>
          <% end %>
          <%= link_to menu_path(menu, page: params[:page]), method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="material-icons">delete</i>
          <% end %>  
        </td>
      </tr>
    <%end%>    
  </tbody>
  <tfoot>
    <tr>
      <th colspan="6">
        <ul class="pagination right-align">
          <% if @menus_count > 0 %>
            <% if !params[:page].present? || (params[:page].present? && params[:page].to_i == 1) %>
              <li class="disabled"><a href="javascript:void(0)"><i class="material-icons">chevron_left</i></a></li>
            <% else %>
              <li class="waves-effect"><a href="/menus?page=<%= params[:page].to_i - 1 %>"><i class="material-icons">chevron_left</i></a></li>
            <% end %>
            <% (1..(@menus_count)).each do |menu| %>
              <li class="<%= ((params[:page].nil? && menu == 1) || params[:page].to_i == menu) ? 'active blue' : 'waves-effect'%>"><a href='<%= ((params[:page].nil? && menu == 1) || params[:page].to_i == menu) ? "javascript:void(0)" : "/menus?page=#{menu}" %>'><%= menu %></a></li>
            <% end %>
            <% if (params[:page].present? && params[:page].to_i == (@menus_count)) %>
              <li class="disabled"><a href="javascript:void(0)"><i class="material-icons">chevron_right</i></a></li>
            <% else %>  
              <li class="waves-effect"><a href="/menus?page=<%= params[:page].to_i + 1 %>"><i class="material-icons">chevron_right</i></a></li>
            <% end %>
          <% end %>
        </ul>
      </th>
    </tr>
  </tfoot>
</table> 

app/views/menus/new.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s9">
      <h4>Add Menu Item</h4>
    </div>
  </div>
  <div class="row">
    <%= form_for(@menu, url: menus_path(), class: "col s12", validate: true) do |f| %>
      <div class="row">
        <%= render "form", f: f %>
        <div class="input-field col s12">
          <button type="submit" name="commit" value="Add Menu" class="waves-effect waves-light btn col s12" data-disable-with="Add Menu">Add Menu</bottun>
        </div>
      </div>
    <% end %>
  </div>
</div>