config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  devise_for :users, path_names:{
    :sign_in => 'login',
    :sign_out => 'logout' 
  }, 
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
   
  resources :menus
  resources :orders do
    collection do
      get "get_menu"
      post "filter_data"
    end
  end
  resources :sales_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sales_users_controller.rb
class SalesUsersController < ApplicationController
  before_action :check_role
  before_action :set_sales_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.where(role_id: 2).paginate(:page => params[:page]).order(id: :asc)
    # @users = User.all.order(id: :asc)
    @users_count = @users.count/User.per_page
    unless @users.count%User.per_page == 0
      @users_count = @users_count + 1
    end
  end

 
  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(sales_users_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to sales_users_path, notice: 'New Sales Person is created successfuly.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @user.update(sales_users_params)
        format.html { redirect_to sales_users_path, notice: 'Sales User is updated successfully.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.discarded_at = Time.now
    @user.save(validate: false)
    respond_to do |format|
      format.html { redirect_to sales_users_path(page: params[:page]), notice: 'Sales User is successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_role
      if current_user.role.name == "Sales"
        redirect_to root_path, notice: "You have not permission to access Menu Items."
      end
    end

    def set_sales_user
      @user = User.find(params[:id])
    end

    def sales_users_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id, :pay_scale)
    end
end

app/helpers/sales_users_helper.rb
module SalesUsersHelper
end

app/views/sales_users/_form.html.erb
<%= f.hidden_field :role_id, value: 2 %>
<div class="input-field col s12">
  <i class="material-icons prefix">person_outline</i>
  <%= f.text_field :first_name, validate: true, autocomplete: "first_name" %>
  <%= f.label :first_name %>
  <span class="helper-text" data-error=""></span>
</div>

<div class="input-field col s12">
  <i class="material-icons prefix">person_outline</i>
  <%= f.text_field :last_name, autocomplete: "last_name" %>
  <%= f.label :last_name %>
  <span class="helper-text" data-error=""></span>
</div>
<div class="input-field col s12">
  <i class="material-icons prefix">email</i>
  <%= f.email_field :email, validate: true, autocomplete: "email", class: "validate" %>
  <%= f.label :email %>
  <span class="helper-text" data-error=""></span>
</div>
<div class="input-field col s12">
  <i class="material-icons prefix">lock_outline</i>
  <%= f.password_field :password, validate: { presence: true, length: true }, autocomplete: "off" ,class: "validate"%>
  <%= f.label :password %>
  <span class="helper-text" data-error="" ><% if @minimum_password_length %><em>(<%= @minimum_password_length %> characters minimum)</em><% end %></span>
</div>
<div class="input-field col s12">
  <i class="material-icons prefix">lock_outline</i>
  <%= f.password_field :password_confirmation, autocomplete: "off" ,class: "validate"%>
  <%= f.label :password_confirmation %>
  <span class="helper-text" data-error="" ></span>
</div>
<div class="input-field col s12">
  <i class="material-icons prefix">attach_money</i>
  <%= f.number_field :pay_scale ,class: "validate"%>
  <%= f.label :pay_scale %>
  <span class="helper-text" data-error="" ></span>
</div>

app/views/sales_users/edit.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s9">
      <h4>Edit Sales User</h4>
    </div>
  </div>
  <div class="row">
    <%= form_for(@user, url: sales_user_path(), class: "col s12", validate: true) do |f| %>
      <div class="row">
        <%= render "form", f: f %>
        <div class="input-field col s12">
          <button type="submit" name="commit" value="Update Sales User" class="waves-effect waves-light btn col s12" data-disable-with="Update Sales User">Update Sales User</bottun>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sales_users/index.html.erb
<div class="row">
  <div class="col s9">
    <h3>Sales Users</h3>
  </div>
  <div class="col s3 right-align">
    <%= link_to new_sales_user_path, class: "btn-floating btn-large waves-effect waves-light red margin-top-15" do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
</div>
<table class="responsive-table centered">
  <thead>
    <tr>
        <th>Sr. No</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, index|%>
      <tr>
        <td><%= params[:page].present? ? (((params[:page].to_i - 1) * User.per_page)  + index + 1) : index + 1 %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to edit_sales_user_path(user) do %>
            <i class="material-icons">edit</i>
          <% end %>
          <%= link_to sales_user_path(user, page: params[:page]), method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="material-icons">delete</i>
          <% end %>  
        </td>
      </tr>
    <%end%>    
  </tbody>
  <tfoot>
    <tr>
      <th colspan="6">
        <ul class="pagination right-align">
          <% if @users_count > 0 %>
            <% if !params[:page].present? || (params[:page].present? && params[:page].to_i == 1) %>
              <li class="disabled"><a href="javascript:void(0)"><i class="material-icons">chevron_left</i></a></li>
            <% else %>
              <li class="waves-effect"><a href="/sales_users?page=<%= params[:page].to_i - 1 %>"><i class="material-icons">chevron_left</i></a></li>
            <% end %>
            <% (1..(@users_count)).each do |user| %>
              <li class="<%= ((params[:page].nil? && user == 1) || params[:page].to_i == user) ? 'active blue' : 'waves-effect'%>"><a href='<%= ((params[:page].nil? && user == 1) || params[:page].to_i == user) ? "javascript:void(0)" : "/sales_users?page=#{user}" %>'><%= user %></a></li>
            <% end %>
            <% if (params[:page].present? && params[:page].to_i == (@users_count)) %>
              <li class="disabled"><a href="javascript:void(0)"><i class="material-icons">chevron_right</i></a></li>
            <% else %>  
              <li class="waves-effect"><a href="/sales_users?page=<%= params[:page].to_i + 1 %>"><i class="material-icons">chevron_right</i></a></li>
            <% end %>
          <% end %>
        </ul>
      </th>
    </tr>
  </tfoot>
</table> 

app/views/sales_users/new.html.erb
<div class="card-panel">
  <div class="row">
    <div class="col s9">
      <h4>Add Sales User</h4>
    </div>
  </div>
  <div class="row">
    <%= form_for(@user, url: sales_users_path(), class: "col s12", validate: true) do |f| %>
      <div class="row">
        <%= render "form", f: f %>
        <div class="input-field col s12">
          <button type="submit" name="commit" value="Add Sales User" class="waves-effect waves-light btn col s12" data-disable-with="Add Sales User">Add Sales User</bottun>
        </div>
      </div>
    <% end %>
  </div>
</div>