config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  devise_for :users, path_names:{
    :sign_in => 'login',
    :sign_out => 'logout' 
  }, 
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
   
  resources :menus
  resources :orders do
    collection do
      get "get_menu"
      post "filter_data"
    end
  end
  resources :sales_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper nav-container">
    <%= link_to root_path, class: "logo-container" do %>
      <%= image_tag("coffee-shop-logo.png", class: "logo-height") %>
    <% end %>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
          <%= link_to "Order", orders_path, class:"navbar-item" %>
        </li>
        <% if current_user.role.name == "Manager" %>
          <li>
            <%= link_to "Menu", menus_path, class:"navbar-item" %>
          </li>
          <li>
            <%= link_to "Sales Users", sales_users_path, class:"navbar-item" %>
          </li>
          <% end %>
        <li>
          <%= link_to current_user.full_name, edit_user_registration_path, class:"navbar-item" %>
        </li>
        <li>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
        </li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="sidenav">
      <li><a href="#">Navbar Link</a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Travis' Coffee Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <main>
      <p class="notice hide"><%= notice %></p>
      <p class="alert hide"><%= alert %></p>
    </main>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>